;;; ruby-test-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ruby-test-mode.el

(autoload 'ruby-test-mode "ruby-test-mode" "\
Toggle Ruby-Test minor mode.

With no argument, this command toggles the mode. Non-null prefix
argument turns on the mode. Null prefix argument turns off the
mode.

This is a minor mode.  If called interactively, toggle the
`Ruby-Test mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `ruby-test-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'ruby-test-run "ruby-test-mode" "\
Run the current buffer's file as specification or unit test." t)
(autoload 'ruby-test-run-at-point "ruby-test-mode" "\
Run test at point individually, using the same search strategy as `ruby-test-run-file'." t)
(autoload 'ruby-test-rerun "ruby-test-mode" "\
Rerun the last test that was run by ruby-test.

When no tests had been run before calling this function, do nothing." t)
(autoload 'ruby-test-toggle-implementation-and-specification "ruby-test-mode" "\
Toggle between the implementation and specification/test file for the current buffer or the optional FILENAME.

(fn &optional FILENAME)" t)
(register-definition-prefixes "ruby-test-mode" '("find-all" "ruby-test-"))

;;; End of scraped data

(provide 'ruby-test-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ruby-test-mode-autoloads.el ends here
