;;; changelog-url-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from changelog-url.el

(autoload 'changelog-url-buttonize "changelog-url")
(register-definition-prefixes "changelog-url" '("changelog-"))

;;; End of scraped data

(provide 'changelog-url-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; changelog-url-autoloads.el ends here
